In [1]:
import pandas as pd
import numpy as np
import getschools as gs

In [54]:
def get_df(group="all"):
    
    ret = pd.read_csv("../clean/csv/sbac-trend-"+group+".csv")
    
    ret["district_code"] = ret["district_code"].astype(str).str.zfill(7)
    ret["school_code"] = ret["school_code"].astype(str).str.zfill(7)
    
    
    ret = gs.add_drg(ret)
    
    return ret

get_df("race")

,district,district_code,school,school_code,subject,race,total_numberof_students,total_numbertested,smarter_balancedparticipationrate,total_number_with_scored_tests,...,level_2approaching_level_2_approaching_count,level_2approaching_pct,level_3met_level_3_met_count,level_3met_pct,level_4exceeded_level_4_exceeded_count,level_4exceeded_pct,level_3_4met_or_exceeded_level_3_4_met_or_exceeded_count,level_3_4met_or_exceeded_pct,year,drg
0,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,American Indian or Alaska Native,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
1,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
2,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,Black or African American,430,428,99.5,427,...,113,26.5,129,30.2,49,11.5,178,41.7,2014-15,None
3,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,Hispanic/Latino of any race,110,109,99.1,109,...,25,22.9,35,32.1,8,7.3,43,39.4,2014-15,None
4,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,Native Hawaiian or Other Pacific Islander,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
5,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,Two or More Races,7,7,*,7,...,*,*,*,*,*,*,*,*,2014-15,None
6,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,ELA,White,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
7,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,American Indian or Alaska Native,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
8,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
9,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,Black or African American,430,427,99.3,426,...,128,30.0,85,20.0,28,6.6,113,26.5,2014-15,None
10,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,Hispanic/Latino of any race,110,109,99.1,109,...,32,29.4,*,*,*,*,24,22.0,2014-15,None
11,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,Native Hawaiian or Other Pacific Islander,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
12,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,Two or More Races,7,7,*,7,...,*,*,*,*,*,*,*,*,2014-15,None
13,Achievement First Hartford Academy Inc. District,2880013,Achievement First Hartford Academy Inc.,2880113,Math,White,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,None
14,Amistad Academy District,2790013,Amistad Academy,2795113,ELA,Black or African American,327,325,99.4,325,...,99,30.5,96,29.5,52,16.0,148,45.5,2014-15,None
15,Amistad Academy District,2790013,Amistad Academy,2795113,ELA,Hispanic/Latino of any race,200,199,99.5,199,...,49,24.6,62,31.2,41,20.6,103,51.8,2014-15,None
16,Amistad Academy District,2790013,Amistad Academy,2795113,ELA,Two or More Races,9,9,*,9,...,*,*,*,*,*,*,*,*,2014-15,None
17,Amistad Academy District,2790013,Amistad Academy,2795113,ELA,White,8,8,*,8,...,*,*,*,*,*,*,*,*,2014-15,None
18,Amistad Academy District,2790013,Amistad Academy,2795113,Math,Black or African American,327,325,99.4,325,...,121,37.2,70,21.5,28,8.6,98,30.2,2014-15,None
19,Amistad Academy District,2790013,Amistad Academy,2795113,Math,Hispanic/Latino of any race,200,198,99.0,198,...,61,30.8,45,22.7,35,17.7,80,40.4,2014-15,None
20,Amistad Academy District,2790013,Amistad Academy,2795113,Math,Two or More Races,9,9,*,9,...,*,*,*,*,*,*,*,*,2014-15,None
21,Amistad Academy District,2790013,Amistad Academy,2795113,Math,White,8,8,*,8,...,*,*,*,*,*,*,*,*,2014-15,None
22,Andover School District,0010011,Andover Elementary School,0010111,ELA,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,C
23,Andover School District,0010011,Andover Elementary School,0010111,ELA,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,C
24,Andover School District,0010011,Andover Elementary School,0010111,ELA,Hispanic/Latino of any race,6,6,*,6,...,*,*,*,*,*,*,*,*,2014-15,C
25,Andover School District,0010011,Andover Elementary School,0010111,ELA,Two or More Races,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,C
26,Andover School District,0010011,Andover Elementary School,0010111,ELA,White,155,152,98.1,152,...,*,*,40,26.3,81,53.3,121,79.6,2014-15,C
27,Andover School District,0010011,Andover Elementary School,0010111,Math,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,C
28,Andover School District,0010011,Andover Elementary School,0010111,Math,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2014-15,C
29,Andover School District,0010011,Andover Elementary School,0010111,Math,Hispanic/Latino of any race,6,6,*,6,...,*,*,*,*,*,*,*,*,2014-15,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19652,Woodbridge School District,1670011,Beecher Road School,1670311,ELA,Black or African American,16,14,*,14,...,*,*,*,*,*,*,*,*,2015-16,B
19653,Woodbridge School District,1670011,Beecher Road School,1670311,ELA,Hispanic/Latino of any race,26,26,100.0,26,...,*,*,10,38.5,8,30.8,18,69.2,2015-16,B
19654,Woodbridge School District,1670011,Beecher Road School,1670311,ELA,Native Hawaiian or Other Pacific Islander,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,B
19655,Woodbridge School District,1670011,Beecher Road School,1670311,ELA,Two or More Races,8,8,*,8,...,*,*,*,*,*,*,*,*,2015-16,B
19656,Woodbridge School District,1670011,Beecher Road School,1670311,ELA,White,310,293,94.5,293,...,36,12.3,90,30.7,145,49.5,235,80.2,2015-16,B
19657,Woodbridge School District,1670011,Beecher Road School,1670311,Math,American Indian or Alaska Native,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,B
19658,Woodbridge School District,1670011,Beecher Road School,1670311,Math,Asian,74,74,100.0,74,...,*,*,18,24.3,45,60.8,63,85.1,2015-16,B
19659,Woodbridge School District,1670011,Beecher Road School,1670311,Math,Black or African American,16,14,*,14,...,*,*,*,*,*,*,*,*,2015-16,B
19660,Woodbridge School District,1670011,Beecher Road School,1670311,Math,Hispanic/Latino of any race,26,26,100.0,26,...,9,34.6,9,34.6,*,*,*,*,2015-16,B
19661,Woodbridge School District,1670011,Beecher Road School,1670311,Math,Native Hawaiian or Other Pacific Islander,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,B
19662,Woodbridge School District,1670011,Beecher Road School,1670311,Math,Two or More Races,8,8,*,8,...,*,*,*,*,*,*,*,*,2015-16,B
19663,Woodbridge School District,1670011,Beecher Road School,1670311,Math,White,310,292,94.2,292,...,62,21.2,96,32.9,109,37.3,205,70.2,2015-16,B
19664,Woodstock School District,1690011,Woodstock Elementary School,1690211,ELA,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19665,Woodstock School District,1690011,Woodstock Elementary School,1690211,ELA,Hispanic/Latino of any race,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19666,Woodstock School District,1690011,Woodstock Elementary School,1690211,ELA,Two or More Races,9,9,*,9,...,*,*,*,*,*,*,*,*,2015-16,E
19667,Woodstock School District,1690011,Woodstock Elementary School,1690211,ELA,White,145,143,98.6,143,...,21,14.7,44,30.8,69,48.3,113,79.0,2015-16,E
19668,Woodstock School District,1690011,Woodstock Elementary School,1690211,Math,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19669,Woodstock School District,1690011,Woodstock Elementary School,1690211,Math,Hispanic/Latino of any race,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19670,Woodstock School District,1690011,Woodstock Elementary School,1690211,Math,Two or More Races,9,9,*,9,...,*,*,*,*,*,*,*,*,2015-16,E
19671,Woodstock School District,1690011,Woodstock Elementary School,1690211,Math,White,145,143,98.6,143,...,50,35.0,61,42.7,25,17.5,86,60.1,2015-16,E
19672,Woodstock School District,1690011,Woodstock Middle School,1695111,ELA,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19673,Woodstock School District,1690011,Woodstock Middle School,1695111,ELA,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19674,Woodstock School District,1690011,Woodstock Middle School,1695111,ELA,Hispanic/Latino of any race,11,10,*,10,...,*,*,*,*,*,*,*,*,2015-16,E
19675,Woodstock School District,1690011,Woodstock Middle School,1695111,ELA,Two or More Races,11,9,*,9,...,*,*,*,*,*,*,*,*,2015-16,E
19676,Woodstock School District,1690011,Woodstock Middle School,1695111,ELA,White,388,372,95.9,372,...,73,19.6,148,39.8,99,26.6,247,66.4,2015-16,E
19677,Woodstock School District,1690011,Woodstock Middle School,1695111,Math,Asian,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19678,Woodstock School District,1690011,Woodstock Middle School,1695111,Math,Black or African American,*,*,*,*,...,*,*,*,*,*,*,*,*,2015-16,E
19679,Woodstock School District,1690011,Woodstock Middle School,1695111,Math,Hispanic/Latino of any race,11,10,*,10,...,*,*,*,*,*,*,*,*,2015-16,E
19680,Woodstock School District,1690011,Woodstock Middle School,1695111,Math,Two or More Races,11,9,*,9,...,*,*,*,*,*,*,*,*,2015-16,E
19681,Woodstock School District,1690011,Woodstock Middle School,1695111,Math,White,388,371,95.6,371,...,118,31.8,104,28.0,76,20.5,180,48.5,2015-16,E

In [55]:
def drg_report(df, groups=[]):
    ret = df.copy()
    
    def to_numeric(col):
        ret[col] = pd.to_numeric(ret[col], errors="coerce")
        
    to_numeric("smarter_balancedparticipationrate")
    to_numeric('total_numberof_students')
    to_numeric('total_numbertested')
    to_numeric('total_number_with_scored_tests')
    
    
    for c in ['level_1not_met_level_1_not_met_count', 
              u'level_1not_met_pct',
              u'level_2approaching_level_2_approaching_count',
              u'level_2approaching_pct', 
              u'level_3met_level_3_met_count',
              u'level_3met_pct', 
              u'level_4exceeded_level_4_exceeded_count',
              u'level_4exceeded_pct',
              u'level_3_4met_or_exceeded_level_3_4_met_or_exceeded_count',
              u'level_3_4met_or_exceeded_pct']:
        
        to_numeric(c)
        
    ret = ret.groupby(["drg","subject", "year"] + groups).agg({
            'total_numberof_students':np.sum,
            'total_numbertested':np.sum,
            'smarter_balancedparticipationrate':np.median,
            'total_number_with_scored_tests':np.sum,
            
            'level_1not_met_pct':np.median,
            'level_2approaching_pct':np.median,
            'level_3met_pct':np.median,
            'level_4exceeded_pct':np.median,
            'level_3_4met_or_exceeded_pct':np.median
            
        }).reset_index()
    
    return ret

drg_report(get_df("race"),
           groups=["race"])

,drg,subject,year,race,total_number_with_scored_tests,level_1not_met_pct,level_3_4met_or_exceeded_pct,total_numberof_students,level_2approaching_pct,smarter_balancedparticipationrate,level_3met_pct,level_4exceeded_pct,total_numbertested
0,A,ELA,2014-15,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A,ELA,2014-15,Asian,856.0,0.00,87.40,919.0,0.00,98.5,41.70,64.20,856.0
2,A,ELA,2014-15,Black or African American,82.0,NaN,NaN,87.0,NaN,NaN,NaN,NaN,82.0
3,A,ELA,2014-15,Hispanic/Latino of any race,579.0,18.85,64.25,631.0,31.80,100.0,43.65,29.50,580.0
4,A,ELA,2014-15,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,A,ELA,2014-15,Two or More Races,248.0,NaN,75.35,258.0,NaN,100.0,37.30,39.70,249.0
6,A,ELA,2014-15,White,12916.0,5.10,83.00,13998.0,12.80,98.0,31.60,50.45,12945.0
7,A,ELA,2015-16,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,A,ELA,2015-16,Asian,814.0,0.00,90.75,816.0,4.70,100.0,33.85,56.85,814.0
9,A,ELA,2015-16,Black or African American,42.0,0.00,NaN,42.0,33.30,NaN,NaN,NaN,42.0
10,A,ELA,2015-16,Hispanic/Latino of any race,549.0,18.90,69.40,555.0,28.45,100.0,36.40,31.60,550.0
11,A,ELA,2015-16,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,A,ELA,2015-16,Two or More Races,327.0,0.00,80.60,332.0,0.00,100.0,34.40,48.30,327.0
13,A,ELA,2015-16,White,11464.0,5.20,83.30,11684.0,12.80,98.6,28.20,57.40,11468.0
14,A,Math,2014-15,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,A,Math,2014-15,Asian,861.0,0.00,85.10,919.0,19.80,100.0,20.70,58.10,861.0
16,A,Math,2014-15,Black or African American,82.0,NaN,NaN,87.0,NaN,NaN,NaN,NaN,82.0
17,A,Math,2014-15,Hispanic/Latino of any race,578.0,24.15,43.95,631.0,31.80,100.0,26.00,30.30,578.0
18,A,Math,2014-15,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,A,Math,2014-15,Two or More Races,247.0,18.20,76.20,258.0,21.20,100.0,30.35,41.20,247.0
20,A,Math,2014-15,White,12868.0,7.50,69.50,13999.0,20.90,97.9,34.05,36.85,12886.0
21,A,Math,2015-16,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,A,Math,2015-16,Asian,814.0,0.00,86.70,816.0,0.00,100.0,21.90,62.95,814.0
23,A,Math,2015-16,Black or African American,42.0,NaN,NaN,42.0,47.60,NaN,NaN,NaN,42.0
24,A,Math,2015-16,Hispanic/Latino of any race,549.0,20.85,59.10,555.0,30.20,100.0,29.30,27.75,550.0
25,A,Math,2015-16,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,A,Math,2015-16,Two or More Races,327.0,0.00,74.60,332.0,29.00,100.0,24.55,53.35,327.0
27,A,Math,2015-16,White,11446.0,5.50,76.40,11686.0,18.80,98.6,30.90,43.30,11452.0
28,B,ELA,2014-15,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,B,ELA,2014-15,Asian,3859.0,0.00,84.75,4009.0,13.50,100.0,33.30,54.35,3860.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,H,Math,2015-16,Two or More Races,505.0,37.00,28.60,510.0,37.50,100.0,NaN,0.00,505.0
223,H,Math,2015-16,White,9338.0,22.60,51.50,9468.0,30.20,100.0,29.20,23.60,9338.0
224,I,ELA,2014-15,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,I,ELA,2014-15,Asian,598.0,34.00,28.60,645.0,31.40,100.0,40.70,50.00,603.0
226,I,ELA,2014-15,Black or African American,13768.0,50.15,20.30,14425.0,29.60,99.2,22.90,3.95,13837.0
227,I,ELA,2014-15,Hispanic/Latino of any race,22914.0,51.00,19.80,24285.0,27.70,98.2,19.90,5.00,23027.0
228,I,ELA,2014-15,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,I,ELA,2014-15,Two or More Races,489.0,30.40,42.90,504.0,38.10,100.0,33.30,22.60,490.0
230,I,ELA,2014-15,White,6448.0,32.05,45.50,6700.0,26.60,98.6,32.00,18.95,6461.0
231,I,ELA,2015-16,American Indian or Alaska Native,18.0,NaN,NaN,18.0,NaN,NaN,NaN,NaN,18.0
232,I,ELA,2015-16,Asian,651.0,36.40,49.15,644.0,31.80,100.0,35.90,49.15,652.0
233,I,ELA,2015-16,Black or African American,12181.0,50.00,21.50,12282.0,26.60,100.0,21.60,5.20,12191.0
234,I,ELA,2015-16,Hispanic/Latino of any race,22598.0,51.00,22.40,22725.0,26.50,100.0,20.10,5.40,22604.0
235,I,ELA,2015-16,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
236,I,ELA,2015-16,Two or More Races,406.0,41.00,20.50,407.0,31.85,100.0,30.20,0.00,406.0
237,I,ELA,2015-16,White,5941.0,31.75,48.40,5999.0,26.00,100.0,32.30,19.55,5949.0
238,I,Math,2014-15,American Indian or Alaska Native,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,I,Math,2014-15,Asian,638.0,47.60,44.65,646.0,30.70,100.0,30.00,41.90,638.0
240,I,Math,2014-15,Black or African American,13790.0,67.50,8.70,14421.0,26.70,99.8,6.70,0.00,13798.0
241,I,Math,2014-15,Hispanic/Latino of any race,23467.0,64.80,9.85,24291.0,27.70,99.1,7.30,0.00,23525.0
242,I,Math,2014-15,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
243,I,Math,2014-15,Two or More Races,490.0,48.25,32.10,498.0,33.50,100.0,13.05,0.00,490.0
244,I,Math,2014-15,White,6503.0,40.70,29.50,6694.0,32.95,100.0,26.20,12.50,6512.0
245,I,Math,2015-16,American Indian or Alaska Native,18.0,NaN,NaN,18.0,NaN,NaN,NaN,NaN,18.0
246,I,Math,2015-16,Asian,650.0,53.85,71.00,644.0,38.50,100.0,19.40,51.60,651.0
247,I,Math,2015-16,Black or African American,12129.0,62.50,13.10,12261.0,28.10,100.0,12.70,0.00,12138.0
248,I,Math,2015-16,Hispanic/Latino of any race,22538.0,58.80,12.50,22729.0,30.20,100.0,11.40,1.60,22549.0
249,I,Math,2015-16,Native Hawaiian or Other Pacific Islander,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
250,I,Math,2015-16,Two or More Races,405.0,40.00,23.90,407.0,43.35,100.0,NaN,0.00,405.0
251,I,Math,2015-16,White,5922.0,38.70,28.80,5998.0,32.35,100.0,23.60,14.10,5931.0

In [56]:
def state_report(df,groups=[]):
    ret = df.copy()
    
    def to_numeric(col):
        ret[col] = pd.to_numeric(ret[col], errors="coerce")
        
    to_numeric("smarter_balancedparticipationrate")
    to_numeric('total_numberof_students')
    to_numeric('total_numbertested')
    to_numeric('total_number_with_scored_tests')
    
    
    for c in ['level_1not_met_level_1_not_met_count', 
              u'level_1not_met_pct',
              u'level_2approaching_level_2_approaching_count',
              u'level_2approaching_pct', 
              u'level_3met_level_3_met_count',
              u'level_3met_pct', 
              u'level_4exceeded_level_4_exceeded_count',
              u'level_4exceeded_pct',
              u'level_3_4met_or_exceeded_level_3_4_met_or_exceeded_count',
              u'level_3_4met_or_exceeded_pct']:
        
        to_numeric(c)
    
    ret = ret.groupby(["year","subject"] + groups).agg({
            'total_numberof_students':np.sum,
            'total_numbertested':np.sum,
            'smarter_balancedparticipationrate':np.median,
            'total_number_with_scored_tests':np.sum,
            
            'level_1not_met_pct':np.median,
            'level_2approaching_pct':np.median,
            'level_3met_pct':np.median,
            'level_4exceeded_pct':np.median,
            'level_3_4met_or_exceeded_pct':np.median
            
        }).reset_index()

    return ret

state_report(get_df())

,year,subject,total_number_with_scored_tests,level_1not_met_pct,level_3_4met_or_exceeded_pct,total_numberof_students,level_2approaching_pct,smarter_balancedparticipationrate,level_3met_pct,level_4exceeded_pct,total_numbertested
0,2014-15,ELA,261639.0,19.00,56.80,273902.0,23.7,98.55,31.20,22.90,262297.0
1,2014-15,Math,262680.0,28.25,39.55,273892.0,29.4,99.00,26.30,15.30,263035.0
2,2015-16,ELA,230037.0,19.20,58.20,232828.0,21.9,99.50,29.15,25.30,230138.0
3,2015-16,Math,229491.0,22.05,46.90,232770.0,28.8,99.40,27.20,20.05,229589.0

In [57]:
get_df("race").to_csv("../clean/for_db/sbac_race.csv",index=False)
drg_report(get_df("race"),groups=["race"]).to_csv("../clean/for_db/drg_sbac_race.csv",index=False)

In [58]:
get_df("all").to_csv("../clean/for_db/sbac_all.csv",index=False)
drg_report(get_df("all")).to_csv("../clean/for_db/drg_sbac_all.csv",index=False)

In [26]:
def state_report_2(group):
    ret = pd.read_csv("../raw/sbac-2015-16-"+group+"-state.csv",skiprows=3,header=None)
    ret = gs.merge_01(ret)

    ret = gs.clean_colnames(ret)
    ret["year"] = "2015-16"
    
    return ret

state_report_2("all").to_csv("../clean/for_db/state_sbac_all_2015_16.csv",index=False)

In [27]:
state_report_2("ell").to_csv("../clean/for_db/state_sbac_ell_2015_16.csv",index=False)

In [29]:
state_report_2("race").to_csv("../clean/for_db/state_sbac_race_2015_16.csv",index=False)