In [1]:
import pandas as pd
import getschools as gs
import numpy as np

In [2]:
def get_df():
    sheetname = "../scripts/noequals/fiscalResources.csv"
    
    ret = pd.read_csv(sheetname,skiprows=4)
    ret["District"] = ret["District"].fillna(method='ffill')
    ret = gs.clean_colnames(ret)
    ret["school"] = ret["district"]
    ret = gs.add_district_matches(ret)
    ret["district_code"] = ret["dist_code"]
    ret = gs.add_drg(ret)
    return ret

get_df()[get_df()["district"] == "Hartford School District"]

,district,type,2010_11,2011_12,2012_13,2013_14,2014_15,school,dist_code,check_dist_col,district_code,drg
670,Hartford School District,Instructional Staff and Services,190625798.0,192251811.0,194221360.0,194348611.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
671,Hartford School District,Instructional Supplies and Equipment,12843318.0,6997940.0,10764164.0,11314153.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
672,Hartford School District,Instruction and Educational Media Services,7350042.0,6716890.0,7006942.0,9074801.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
673,Hartford School District,Student Support Services,25176993.0,27121589.0,29100518.0,30558051.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
674,Hartford School District,Administration and Support Services,44460967.0,48594069.0,48861848.0,53208272.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
675,Hartford School District,Plant Operation and Maintenance,43040865.0,40439978.0,35200588.0,38940865.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
676,Hartford School District,Transportation,26724310.0,27219201.0,26962976.0,25295126.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
677,Hartford School District,Students Tuitioned Out,39320800.0,41748790.0,48034401.0,55532756.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
678,Hartford School District,Other,288917.0,246188.0,175628.0,206433.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I
679,Hartford School District,Total Expenditures,389832010.0,391336456.0,400328425.0,418479068.0,NaN,Hartford School District,0640011,Hartford School District,0640011,I

In [3]:
df = get_df()
print "bad " + str(len(df[df["dist_code"].isnull()]["district"].unique()))
print "good " + str(len(df[df["dist_code"].notnull()]["district"].unique()))

bad 2
good 187

In [4]:

def get_total(dist_name,year=None):
    #ret = get_df()
    ret = df.copy()
    
    try:
        ret = ret[(ret["district"] == dist_name) & (ret["type"] == "Total Expenditures")]
    except:
        pass
        
    if year is not None:
        ret = ret[year]
    
    try:
        return float(ret)
    except:
        pass

get_total("Woodbridge School District",year="2014_15")

13239947.0

In [5]:
get_total("Fake School District",year="2014_15")

In [6]:
def get_pct(dist_name,amount,year="2014_15"):
    try:
        total = get_total(dist_name,year=year)
    except Exception, e:
        print e
        return
    return amount / total
    
print get_pct("Woodbridge School District",132,year="2014_15")

9.96982842907e-06

In [7]:
def pct_table(year="2014_15"):
    ret = df[["drg","district_code","district","type",year]]
    ret["year"] = year.replace("_","-")
    
    ret.columns = "drg","district_code","district","type","amount","year"
    ret["pct"] = ret.apply(lambda x: get_pct(x["district"],x["amount"],year),axis=1)
    return ret

pct_table()

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct
0,None,2880013,Achievement First Hartford Academy Inc. District,Instructional Staff and Services,6863137.0,2014-15,0.535979
1,None,2880013,Achievement First Hartford Academy Inc. District,Instructional Supplies and Equipment,646646.0,2014-15,0.050500
2,None,2880013,Achievement First Hartford Academy Inc. District,Instruction and Educational Media Services,310629.0,2014-15,0.024259
3,None,2880013,Achievement First Hartford Academy Inc. District,Student Support Services,1086042.0,2014-15,0.084815
4,None,2880013,Achievement First Hartford Academy Inc. District,Administration and Support Services,3699477.0,2014-15,0.288912
5,None,2880013,Achievement First Hartford Academy Inc. District,Plant Operation and Maintenance,83095.0,2014-15,0.006489
6,None,2880013,Achievement First Hartford Academy Inc. District,Transportation,98398.0,2014-15,0.007684
7,None,2880013,Achievement First Hartford Academy Inc. District,Students Tuitioned Out,NaN,2014-15,NaN
8,None,2880013,Achievement First Hartford Academy Inc. District,Other,17440.0,2014-15,0.001362
9,None,2880013,Achievement First Hartford Academy Inc. District,Total Expenditures,12804864.0,2014-15,1.000000
10,None,2790013,Amistad Academy District,Instructional Staff and Services,6249225.0,2014-15,0.516071
11,None,2790013,Amistad Academy District,Instructional Supplies and Equipment,355875.0,2014-15,0.029389
12,None,2790013,Amistad Academy District,Instruction and Educational Media Services,466714.0,2014-15,0.038542
13,None,2790013,Amistad Academy District,Student Support Services,1218680.0,2014-15,0.100641
14,None,2790013,Amistad Academy District,Administration and Support Services,2523973.0,2014-15,0.208434
15,None,2790013,Amistad Academy District,Plant Operation and Maintenance,512598.0,2014-15,0.042331
16,None,2790013,Amistad Academy District,Transportation,191428.0,2014-15,0.015808
17,None,2790013,Amistad Academy District,Students Tuitioned Out,NaN,2014-15,NaN
18,None,2790013,Amistad Academy District,Other,590732.0,2014-15,0.048784
19,None,2790013,Amistad Academy District,Total Expenditures,12109225.0,2014-15,1.000000
20,C,0010011,Andover School District,Instructional Staff and Services,2712516.0,2014-15,0.610694
21,C,0010011,Andover School District,Instructional Supplies and Equipment,122533.0,2014-15,0.027587
22,C,0010011,Andover School District,Instruction and Educational Media Services,84239.0,2014-15,0.018966
23,C,0010011,Andover School District,Student Support Services,157766.0,2014-15,0.035519
24,C,0010011,Andover School District,Administration and Support Services,615105.0,2014-15,0.138484
25,C,0010011,Andover School District,Plant Operation and Maintenance,489907.0,2014-15,0.110297
26,C,0010011,Andover School District,Transportation,192339.0,2014-15,0.043303
27,C,0010011,Andover School District,Students Tuitioned Out,67287.0,2014-15,0.015149
28,C,0010011,Andover School District,Other,0.0,2014-15,0.000000
29,C,0010011,Andover School District,Total Expenditures,4441692.0,2014-15,1.000000
...,...,...,...,...,...,...,...
1860,F,1660011,Wolcott School District,Instructional Staff and Services,21096780.0,2014-15,0.600973
1861,F,1660011,Wolcott School District,Instructional Supplies and Equipment,646167.0,2014-15,0.018407
1862,F,1660011,Wolcott School District,Instruction and Educational Media Services,718869.0,2014-15,0.020478
1863,F,1660011,Wolcott School District,Student Support Services,1383667.0,2014-15,0.039416
1864,F,1660011,Wolcott School District,Administration and Support Services,3781598.0,2014-15,0.107724
1865,F,1660011,Wolcott School District,Plant Operation and Maintenance,3649192.0,2014-15,0.103953
1866,F,1660011,Wolcott School District,Transportation,2060096.0,2014-15,0.058685
1867,F,1660011,Wolcott School District,Students Tuitioned Out,1011331.0,2014-15,0.028809
1868,F,1660011,Wolcott School District,Other,756652.0,2014-15,0.021554
1869,F,1660011,Wolcott School District,Total Expenditures,35104352.0,2014-15,1.000000
1870,B,1670011,Woodbridge School District,Instructional Staff and Services,8679380.0,2014-15,0.655545
1871,B,1670011,Woodbridge School District,Instructional Supplies and Equipment,313319.0,2014-15,0.023665
1872,B,1670011,Woodbridge School District,Instruction and Educational Media Services,71708.0,2014-15,0.005416
1873,B,1670011,Woodbridge School District,Student Support Services,185530.0,2014-15,0.014013
1874,B,1670011,Woodbridge School District,Administration and Support Services,2163893.0,2014-15,0.163437
1875,B,1670011,Woodbridge School District,Plant Operation and Maintenance,982778.0,2014-15,0.074228
1876,B,1670011,Woodbridge School District,Transportation,567722.0,2014-15,0.042879
1877,B,1670011,Woodbridge School District,Students Tuitioned Out,275617.0,2014-15,0.020817
1878,B,1670011,Woodbridge School District,Other,0.0,2014-15,0.000000
1879,B,1670011,Woodbridge School District,Total Expenditures,13239947.0,2014-15,1.000000
1880,E,1690011,Woodstock School District,Instructional Staff and Services,7100494.0,2014-15,0.598385
1881,E,1690011,Woodstock School District,Instructional Supplies and Equipment,168338.0,2014-15,0.014186
1882,E,1690011,Woodstock School District,Instruction and Educational Media Services,129340.0,2014-15,0.010900
1883,E,1690011,Woodstock School District,Student Support Services,614702.0,2014-15,0.051803
1884,E,1690011,Woodstock School District,Administration and Support Services,977945.0,2014-15,0.082415
1885,E,1690011,Woodstock School District,Plant Operation and Maintenance,1356609.0,2014-15,0.114326
1886,E,1690011,Woodstock School District,Transportation,986549.0,2014-15,0.083140
1887,E,1690011,Woodstock School District,Students Tuitioned Out,512548.0,2014-15,0.043194
1888,E,1690011,Woodstock School District,Other,19579.0,2014-15,0.001650
1889,E,1690011,Woodstock School District,Total Expenditures,11866104.0,2014-15,1.000000

In [8]:
def one_topic(df, topic="Instructional Staff and Services"):
    
    ret = df.copy()
    
    ret = ret[ret["type"] == topic]
    
    return ret
one_topic(pct_table())[one_topic(pct_table())["district"] == "Hartford School District"]

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct
670,I,0640011,Hartford School District,Instructional Staff and Services,NaN,2014-15,NaN

In [9]:
def describe(df, topic="Instructional Staff and Services"):
    
    ret = one_topic(df, topic)
    
    return ret["pct"].describe()
    
describe(pct_table())

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

count    185.000000
mean       0.543864
std        0.066234
min        0.283608
25%        0.519246
50%        0.547624
75%        0.588601
max        0.686115
Name: pct, dtype: float64

In [10]:
one_topic(pct_table()).sort_values(by="pct").head(10)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct
1650,None,2780013,Trailblazers Academy District,Instructional Staff and Services,1164747.0,2014-15,0.283608
1110,None,2830013,Park City Prep Charter School District,Instructional Staff and Services,1386811.0,2014-15,0.323676
600,None,2940013,Great Oaks Charter School District,Instructional Staff and Services,633266.0,2014-15,0.324244
510,None,2910013,Elm City Montessori School District,Instructional Staff and Services,597554.0,2014-15,0.339707
1400,C,1210011,Salem School District,Instructional Staff and Services,3000813.0,2014-15,0.351276
1540,None,2820013,Stamford Academy District,Instructional Staff and Services,1050120.0,2014-15,0.351598
500,None,2890013,Elm City College Preparatory School District,Instructional Staff and Services,3838899.0,2014-15,0.382782
1120,None,2930013,Path Academy District,Instructional Staff and Services,767584.0,2014-15,0.385738
310,C,0300011,Columbia School District,Instructional Staff and Services,3865952.0,2014-15,0.395469
120,None,2950013,Booker T. Washington Academy District,Instructional Staff and Services,641184.0,2014-15,0.403533

In [11]:
one_topic(pct_table()).sort_values(by="pct",ascending=False).head(10)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct
1200,A,1170011,Redding School District,Instructional Staff and Services,15039819.0,2014-15,0.686115
610,B,0570011,Greenwich School District,Instructional Staff and Services,130429647.0,2014-15,0.677820
480,A,0460011,Easton School District,Instructional Staff and Services,10964816.0,2014-15,0.661051
1870,B,1670011,Woodbridge School District,Instructional Staff and Services,8679380.0,2014-15,0.655545
830,C,0790011,Marlborough School District,Instructional Staff and Services,4916149.0,2014-15,0.650516
360,H,0340011,Danbury School District,Instructional Staff and Services,91588394.0,2014-15,0.649089
1600,None,2690013,The Bridge Academy District,Instructional Staff and Services,2281505.0,2014-15,0.642989
280,D,0270011,Clinton School District,Instructional Staff and Services,20567558.0,2014-15,0.638984
1270,A,2090012,Regional School District 09,Instructional Staff and Services,13560551.0,2014-15,0.638713
1020,F,1000011,North Canaan School District,Instructional Staff and Services,3650206.0,2014-15,0.635644

In [12]:
def drg_summary(df, agg):
    return df.groupby("drg").agg(agg)

drg_summary(one_topic(pct_table()).sort_values(by="pct",ascending=False), {"pct":np.median})

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

          pct
drg
A    0.574718
B    0.563061
C    0.546224
D    0.552050
E    0.542322
F    0.536915
G    0.544471
H    0.547950
I    0.569376

In [13]:
def state_sum(topic="Instructional Staff and Services",year="2014_15"):
    
    ret = df[df["type"] == topic]
    ret = np.nansum(ret[year])
    
    return ret

state_sum()

4603362521.0

In [14]:
def state_pct(topic="Instructional Staff and Services",year="2014_15"):
    return state_sum(topic, year) / state_sum("Total Expenditures")

state_pct()

0.5636078701145345

In [15]:
def state_pct_summary(year="2014_15"):
    
    ret = []
    for t in df["type"].unique():
        ret.append({"type":t,
                  "pct":state_pct(topic=t,year=year),
                 "year":year})
        
    return pd.DataFrame(ret)[["year","type","pct"]].sort_values(by="pct",ascending=False)

state_pct_summary()

      year                                        type       pct
9  2014_15                          Total Expenditures  1.000000
0  2014_15            Instructional Staff and Services  0.563608
4  2014_15         Administration and Support Services  0.105546
5  2014_15             Plant Operation and Maintenance  0.096864
3  2014_15                    Student Support Services  0.061608
6  2014_15                              Transportation  0.055714
7  2014_15                      Students Tuitioned Out  0.053051
2  2014_15  Instruction and Educational Media Services  0.032929
1  2014_15        Instructional Supplies and Equipment  0.018589
8  2014_15                                       Other  0.012092

In [23]:
def main_frame(year="2014_15"):
    frames = []
    for t in df["type"].unique():
        f = one_topic(pct_table(year=year),topic=t)  
        f["state_pct"] = state_pct(topic=t,year=year)
        frames.append(f)
    ret = pd.concat(frames)
    ret["school_code"] = ret["district_code"]
    
    return ret
#mf = main_frame()

In [24]:
mf = main_frame(year="2013_14")
mf

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct,state_pct,school_code
0,None,2880013,Achievement First Hartford Academy Inc. District,Instructional Staff and Services,6717091.0,2013-14,0.640745,0.578684,2880013
10,None,2790013,Amistad Academy District,Instructional Staff and Services,6610454.0,2013-14,0.537230,0.578684,2790013
20,C,0010011,Andover School District,Instructional Staff and Services,2740679.0,2013-14,0.584505,0.578684,0010011
30,H,0020011,Ansonia School District,Instructional Staff and Services,17277476.0,2013-14,0.513992,0.578684,0020011
40,E,0030011,Ashford School District,Instructional Staff and Services,4502683.0,2013-14,0.604057,0.578684,0030011
50,B,0040011,Avon School District,Instructional Staff and Services,30147184.0,2013-14,0.587087,0.578684,0040011
60,C,0050011,Barkhamsted School District,Instructional Staff and Services,2530127.0,2013-14,0.611082,0.578684,0050011
70,D,0070011,Berlin School District,Instructional Staff and Services,23332208.0,2013-14,0.497912,0.578684,0070011
80,C,0080011,Bethany School District,Instructional Staff and Services,4157960.0,2013-14,0.606172,0.578684,0080011
90,D,0090011,Bethel School District,Instructional Staff and Services,25965355.0,2013-14,0.569282,0.578684,0090011
100,G,0110011,Bloomfield School District,Instructional Staff and Services,22949787.0,2013-14,0.496439,0.578684,0110011
110,C,0120011,Bolton School District,Instructional Staff and Services,7587194.0,2013-14,0.538701,0.578684,0120011
120,None,2950013,Booker T. Washington Academy District,Instructional Staff and Services,NaN,2013-14,NaN,0.578684,2950013
130,E,0130011,Bozrah School District,Instructional Staff and Services,2518670.0,2013-14,0.566577,0.578684,0130011
140,D,0140011,Branford School District,Instructional Staff and Services,29900579.0,2013-14,0.553913,0.578684,0140011
150,None,2900013,Brass City Charter School District,Instructional Staff and Services,541267.0,2013-14,0.416092,0.578684,2900013
160,None,2850013,Bridgeport Achievement First District,Instructional Staff and Services,5654792.0,2013-14,0.509037,0.578684,2850013
170,I,0150011,Bridgeport School District,Instructional Staff and Services,176667378.0,2013-14,0.587376,0.578684,0150011
180,G,0170011,Bristol School District,Instructional Staff and Services,65587827.0,2013-14,0.573782,0.578684,0170011
190,B,0180011,Brookfield School District,Instructional Staff and Services,24302352.0,2013-14,0.598382,0.578684,0180011
200,E,0190011,Brooklyn School District,Instructional Staff and Services,7333678.0,2013-14,0.565983,0.578684,0190011
210,E,0210011,Canaan School District,Instructional Staff and Services,1280526.0,2013-14,0.594205,0.578684,0210011
220,F,0220011,Canterbury School District,Instructional Staff and Services,4918129.0,2013-14,0.521777,0.578684,0220011
230,C,0230011,Canton School District,Instructional Staff and Services,12900895.0,2013-14,0.496744,0.578684,0230011
240,E,0240011,Chaplin School District,Instructional Staff and Services,2136076.0,2013-14,0.594087,0.578684,0240011
250,None,None,Charter School for Young Children on Asylum Hi...,Instructional Staff and Services,NaN,2013-14,NaN,0.578684,None
260,B,0250011,Cheshire School District,Instructional Staff and Services,37531994.0,2013-14,0.573957,0.578684,0250011
270,E,0260011,Chester School District,Instructional Staff and Services,2250518.0,2013-14,0.519986,0.578684,0260011
280,D,0270011,Clinton School District,Instructional Staff and Services,19305103.0,2013-14,0.615913,0.578684,0270011
290,D,0280011,Colchester School District,Instructional Staff and Services,22649592.0,2013-14,0.552661,0.578684,0280011
...,...,...,...,...,...,...,...,...,...
1599,C,1390011,Suffield School District,Total Expenditures,34551716.0,2013-14,1.000000,1.025890,1390011
1609,None,2690013,The Bridge Academy District,Total Expenditures,3446576.0,2013-14,1.000000,1.025890,2690013
1619,E,1400011,Thomaston School District,Total Expenditures,17097774.0,2013-14,1.000000,1.025890,1400011
1629,F,1410011,Thompson School District,Total Expenditures,17330197.0,2013-14,1.000000,1.025890,1410011
1639,C,1420011,Tolland School District,Total Expenditures,39015259.0,2013-14,1.000000,1.025890,1420011
1649,G,1430011,Torrington School District,Total Expenditures,72799765.0,2013-14,1.000000,1.025890,1430011
1659,None,2780013,Trailblazers Academy District,Total Expenditures,4335030.0,2013-14,1.000000,1.025890,2780013
1669,B,1440011,Trumbull School District,Total Expenditures,100859802.0,2013-14,1.000000,1.025890,1440011
1679,E,1450011,Union School District,Total Expenditures,1499673.0,2013-14,1.000000,1.025890,1450011
1689,G,1460011,Vernon School District,Total Expenditures,53774982.0,2013-14,1.000000,1.025890,1460011
1699,F,1470011,Voluntown School District,Total Expenditures,5502486.0,2013-14,1.000000,1.025890,1470011
1709,D,1480011,Wallingford School District,Total Expenditures,108836114.0,2013-14,1.000000,1.025890,1480011
1719,I,1510011,Waterbury School District,Total Expenditures,273229441.0,2013-14,1.000000,1.025890,1510011
1729,D,1520011,Waterford School District,Total Expenditures,46840014.0,2013-14,1.000000,1.025890,1520011
1739,D,1530011,Watertown School District,Total Expenditures,40391211.0,2013-14,1.000000,1.025890,1530011
1749,B,1550011,West Hartford School District,Total Expenditures,148030022.0,2013-14,1.000000,1.025890,1550011
1759,H,1560011,West Haven School District,Total Expenditures,93143526.0,2013-14,1.000000,1.025890,1560011
1769,E,1540011,Westbrook School District,Total Expenditures,16790711.0,2013-14,1.000000,1.025890,1540011
1779,A,1570011,Weston School District,Total Expenditures,48204385.0,2013-14,1.000000,1.025890,1570011
1789,A,1580011,Westport School District,Total Expenditures,111883675.0,2013-14,1.000000,1.025890,1580011
1799,D,1590011,Wethersfield School District,Total Expenditures,56703594.0,2013-14,1.000000,1.025890,1590011
1809,E,1600011,Willington School District,Total Expenditures,8441597.0,2013-14,1.000000,1.025890,1600011
1819,A,1610011,Wilton School District,Total Expenditures,78858238.0,2013-14,1.000000,1.025890,1610011
1829,G,1620011,Winchester School District,Total Expenditures,NaN,2013-14,NaN,1.025890,1620011
1839,I,1630011,Windham School District,Total Expenditures,57387482.0,2013-14,1.000000,1.025890,1630011
1849,F,1650011,Windsor Locks School District,Total Expenditures,32525634.0,2013-14,1.000000,1.025890,1650011
1859,D,1640011,Windsor School District,Total Expenditures,67607901.0,2013-14,1.000000,1.025890,1640011
1869,F,1660011,Wolcott School District,Total Expenditures,34416249.0,2013-14,1.000000,1.025890,1660011
1879,B,1670011,Woodbridge School District,Total Expenditures,13390851.0,2013-14,1.000000,1.025890,1670011
1889,E,1690011,Woodstock School District,Total Expenditures,11920194.0,2013-14,1.000000,1.025890,1690011

In [25]:
def big_mf():
    ret = []
    for y in ["2010_11","2011_12","2012_13","2013_14","2014_15"]:
        ret.append(main_frame(year=y))
        
    return pd.concat(ret)

bmf = big_mf()
bmf

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,drg,district_code,district,type,amount,year,pct,state_pct,school_code
0,None,2880013,Achievement First Hartford Academy Inc. District,Instructional Staff and Services,3797374.0,2010-11,0.533701,0.555348,2880013
10,None,2790013,Amistad Academy District,Instructional Staff and Services,5124861.0,2010-11,0.451055,0.555348,2790013
20,C,0010011,Andover School District,Instructional Staff and Services,2668054.0,2010-11,0.614453,0.555348,0010011
30,H,0020011,Ansonia School District,Instructional Staff and Services,17155560.0,2010-11,0.544190,0.555348,0020011
40,E,0030011,Ashford School District,Instructional Staff and Services,4523087.0,2010-11,0.629655,0.555348,0030011
50,B,0040011,Avon School District,Instructional Staff and Services,26598773.0,2010-11,0.581405,0.555348,0040011
60,C,0050011,Barkhamsted School District,Instructional Staff and Services,2513004.0,2010-11,0.646145,0.555348,0050011
70,D,0070011,Berlin School District,Instructional Staff and Services,22155615.0,2010-11,0.523112,0.555348,0070011
80,C,0080011,Bethany School District,Instructional Staff and Services,4022479.0,2010-11,0.589932,0.555348,0080011
90,D,0090011,Bethel School District,Instructional Staff and Services,24276902.0,2010-11,0.570918,0.555348,0090011
100,G,0110011,Bloomfield School District,Instructional Staff and Services,22290689.0,2010-11,0.514241,0.555348,0110011
110,C,0120011,Bolton School District,Instructional Staff and Services,7380262.0,2010-11,0.569868,0.555348,0120011
120,None,2950013,Booker T. Washington Academy District,Instructional Staff and Services,NaN,2010-11,NaN,0.555348,2950013
130,E,0130011,Bozrah School District,Instructional Staff and Services,2230586.0,2010-11,0.532931,0.555348,0130011
140,D,0140011,Branford School District,Instructional Staff and Services,29515869.0,2010-11,0.579719,0.555348,0140011
150,None,2900013,Brass City Charter School District,Instructional Staff and Services,NaN,2010-11,NaN,0.555348,2900013
160,None,2850013,Bridgeport Achievement First District,Instructional Staff and Services,2184618.0,2010-11,0.393639,0.555348,2850013
170,I,0150011,Bridgeport School District,Instructional Staff and Services,177852907.0,2010-11,0.614186,0.555348,0150011
180,G,0170011,Bristol School District,Instructional Staff and Services,65291611.0,2010-11,0.587588,0.555348,0170011
190,B,0180011,Brookfield School District,Instructional Staff and Services,23070966.0,2010-11,0.609823,0.555348,0180011
200,E,0190011,Brooklyn School District,Instructional Staff and Services,7453096.0,2010-11,0.604673,0.555348,0190011
210,E,0210011,Canaan School District,Instructional Staff and Services,1339639.0,2010-11,0.621233,0.555348,0210011
220,F,0220011,Canterbury School District,Instructional Staff and Services,4599938.0,2010-11,0.510046,0.555348,0220011
230,C,0230011,Canton School District,Instructional Staff and Services,11856616.0,2010-11,0.498212,0.555348,0230011
240,E,0240011,Chaplin School District,Instructional Staff and Services,1967652.0,2010-11,0.582007,0.555348,0240011
250,None,None,Charter School for Young Children on Asylum Hi...,Instructional Staff and Services,1781595.0,2010-11,0.552401,0.555348,None
260,B,0250011,Cheshire School District,Instructional Staff and Services,36182060.0,2010-11,0.577490,0.555348,0250011
270,E,0260011,Chester School District,Instructional Staff and Services,2415990.0,2010-11,0.551975,0.555348,0260011
280,D,0270011,Clinton School District,Instructional Staff and Services,19165924.0,2010-11,0.615581,0.555348,0270011
290,D,0280011,Colchester School District,Instructional Staff and Services,22105615.0,2010-11,0.583089,0.555348,0280011
...,...,...,...,...,...,...,...,...,...
1599,C,1390011,Suffield School District,Total Expenditures,35274951.0,2014-15,1.000000,1.000000,1390011
1609,None,2690013,The Bridge Academy District,Total Expenditures,3548282.0,2014-15,1.000000,1.000000,2690013
1619,E,1400011,Thomaston School District,Total Expenditures,15386891.0,2014-15,1.000000,1.000000,1400011
1629,F,1410011,Thompson School District,Total Expenditures,17097521.0,2014-15,1.000000,1.000000,1410011
1639,C,1420011,Tolland School District,Total Expenditures,39604154.0,2014-15,1.000000,1.000000,1420011
1649,G,1430011,Torrington School District,Total Expenditures,74404141.0,2014-15,1.000000,1.000000,1430011
1659,None,2780013,Trailblazers Academy District,Total Expenditures,4106888.0,2014-15,1.000000,1.000000,2780013
1669,B,1440011,Trumbull School District,Total Expenditures,102893480.0,2014-15,1.000000,1.000000,1440011
1679,E,1450011,Union School District,Total Expenditures,1693725.0,2014-15,1.000000,1.000000,1450011
1689,G,1460011,Vernon School District,Total Expenditures,55179777.0,2014-15,1.000000,1.000000,1460011
1699,F,1470011,Voluntown School District,Total Expenditures,5603583.0,2014-15,1.000000,1.000000,1470011
1709,D,1480011,Wallingford School District,Total Expenditures,101129696.0,2014-15,1.000000,1.000000,1480011
1719,I,1510011,Waterbury School District,Total Expenditures,281159636.0,2014-15,1.000000,1.000000,1510011
1729,D,1520011,Waterford School District,Total Expenditures,47386308.0,2014-15,1.000000,1.000000,1520011
1739,D,1530011,Watertown School District,Total Expenditures,41399976.0,2014-15,1.000000,1.000000,1530011
1749,B,1550011,West Hartford School District,Total Expenditures,153864660.0,2014-15,1.000000,1.000000,1550011
1759,H,1560011,West Haven School District,Total Expenditures,95726473.0,2014-15,1.000000,1.000000,1560011
1769,E,1540011,Westbrook School District,Total Expenditures,16667978.0,2014-15,1.000000,1.000000,1540011
1779,A,1570011,Weston School District,Total Expenditures,49280345.0,2014-15,1.000000,1.000000,1570011
1789,A,1580011,Westport School District,Total Expenditures,116633569.0,2014-15,1.000000,1.000000,1580011
1799,D,1590011,Wethersfield School District,Total Expenditures,59113599.0,2014-15,1.000000,1.000000,1590011
1809,E,1600011,Willington School District,Total Expenditures,8317335.0,2014-15,1.000000,1.000000,1600011
1819,A,1610011,Wilton School District,Total Expenditures,82227662.0,2014-15,1.000000,1.000000,1610011
1829,G,1620011,Winchester School District,Total Expenditures,NaN,2014-15,NaN,1.000000,1620011
1839,I,1630011,Windham School District,Total Expenditures,61787377.0,2014-15,1.000000,1.000000,1630011
1849,F,1650011,Windsor Locks School District,Total Expenditures,32935271.0,2014-15,1.000000,1.000000,1650011
1859,D,1640011,Windsor School District,Total Expenditures,69451322.0,2014-15,1.000000,1.000000,1640011
1869,F,1660011,Wolcott School District,Total Expenditures,35104352.0,2014-15,1.000000,1.000000,1660011
1879,B,1670011,Woodbridge School District,Total Expenditures,13239947.0,2014-15,1.000000,1.000000,1670011
1889,E,1690011,Woodstock School District,Total Expenditures,11866104.0,2014-15,1.000000,1.000000,1690011

In [27]:
bmf.to_csv("../clean/csv/spending.csv",index=False)
bmf.to_csv("../clean/for_db/spending.csv",index=False)

In [26]:
bmf[(bmf["district"] == "Hartford School District") & (bmf["type"] == "Instructional Staff and Services")]

,drg,district_code,district,type,amount,year,pct,state_pct,school_code
670,I,0640011,Hartford School District,Instructional Staff and Services,190625798.0,2010-11,0.488995,0.555348,0640011
670,I,0640011,Hartford School District,Instructional Staff and Services,192251811.0,2011-12,0.491270,0.555253,0640011
670,I,0640011,Hartford School District,Instructional Staff and Services,194221360.0,2012-13,0.485155,0.562845,0640011
670,I,0640011,Hartford School District,Instructional Staff and Services,194348611.0,2013-14,0.464417,0.578684,0640011
670,I,0640011,Hartford School District,Instructional Staff and Services,NaN,2014-15,NaN,0.563608,0640011